### ISSUE TITLE
SyntaxError on published index.esm.js in react-window@1.8.5

### ISSUE THREAD

**Issue by Jessidhia** [bvaughn/react-window#299]
It seems that, in two of the `flushSync` invocations, either an error in the (not yet pushed to github?) source code, or in some postprocessing, the closing parens for the `flushSync` call is placed on the wrong closing bracket.

The code effectively reads as `flushSync(() => { /* ... */ } })` (note the extra `}`), which is a syntax error. This can be fixed locally by removing the `)` on line 1171 and adding it on 1170 before the `;`, a similar fix can be done on the other instance of this same error that happens on the file.

<details>
<summary>Full error message</summary>

```
ERROR in /.../node_modules/react-window/dist/index.esm.js
Module build failed (from /.../node_modules/babel-loader/lib/index.js):
SyntaxError: /.../node_modules/react-window/dist/index.esm.js: Unexpected token, expected "," (1170:9)

  1168 |             };
  1169 |           }, _this._resetIsScrollingDebounced);
> 1170 |         };
       |          ^
  1171 |       });
  1172 |
  1173 |       _this._onScrollVertical = function (event) {
    at Object.raise (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.unexpected (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5143:16)
    at Object.expect (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5135:28)
    at Object.parseCallExpressionArguments (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6055:14)
    at Object.parseSubscript (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5965:29)
    at Object.parseSubscript (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:2746:18)
    at Object.parseSubscripts (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5882:19)
    at Object.parseSubscripts (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:2700:18)
    at Object.parseExprSubscripts (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5872:17)
    at Object.parseMaybeUnary (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5842:21)
    at Object.parseExprOps (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5729:23)
    at Object.parseMaybeConditional (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5702:23)
    at Object.parseMaybeAssign (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5647:21)
    at Object.parseMaybeAssign (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:2621:18)
    at Object.parseExpression (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5595:23)
    at Object.parseStatementContent (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7378:23)
    at Object.parseStatement (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7243:17)
    at Object.parseStatement (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:1977:26)
    at Object.parseBlockOrModuleBlockBody (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7810:25)
    at Object.parseBlockBody (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7797:10)
    at Object.parseBlock (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7786:10)
    at Object.parseFunctionBody (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6876:24)
    at Object.parseFunctionBody (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:1958:18)
    at Object.parseFunctionBodyAndFinish (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6860:10)
    at Object.parseFunctionBodyAndFinish (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:1968:11)
    at /.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7945:12
    at Object.withTopicForbiddingContext (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7150:14)
    at Object.parseFunction (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7944:10)
    at Object.parseFunctionExpression (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6326:17)
    at Object.parseExprAtom (/.../node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6232:21)
 @ /.../src/devtools/views/Components/Tree.js 19:0-45 357:26-39
 @ /.../src/devtools/views/Components/Components.js
 @ /.../src/devtools/views/DevTools.js
 @ ./src/main.js
```
</details>

**Comment by bvaughn** [comment]
What is this referring to? `flushSync` isn't referenced anywhere in the published `react-window`.

**Comment by Jessidhia** [comment]
Yeah, that's the thing I found the strangest. The error comes from the `react-window` that is installed by https://github.com/bvaughn/react-devtools-experimental/ so I suppose the bug is there, not here, as you have a vendored fork in there.

**Comment by bvaughn** [comment]
Hm. Sounds like the merge went poorly.

I'm going to close this issue.
